In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\nawaz\Desktop\python for data engineering\datasets\world_population.csv")
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [4]:
capitals = ['Islamabad', 'Tehran', 'Ankara']
df[df['Capital'].isin(capitals)]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
94,17,IRN,Iran,Tehran,Asia,88550570.0,87290193.0,81790841.0,75373855.0,65544383.0,55793629.0,38520664.0,28449705.0,1648195.0,53.7258,1.0071,1.11
156,5,PAK,Pakistan,Islamabad,Asia,235824862.0,227196741.0,210969298.0,194454498.0,154369924.0,115414069.0,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
213,18,TUR,Turkey,Ankara,Asia,85341241.0,84135428.0,79646178.0,73195345.0,64113547.0,54324142.0,44089069.0,35540990.0,783562.0,108.9145,1.0067,1.07

In [5]:
df[df['Capital'].isin(['Algiers'])]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56

In [6]:
df[df['Country'].str.contains('stan')]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
105,66,KAZ,Kazakhstan,Nursultan,Asia,19397998.0,18979243.0,17835909.0,16627837.0,15236253.0,16866563.0,14172710.0,12265305.0,2724900.0,7.1188,1.0105,0.24
109,110,KGZ,Kyrgyzstan,Bishkek,Asia,6630623.0,6424874.0,5914980.0,5483774.0,4935182.0,4394734.0,3691209.0,3016384.0,199951.0,33.1612,1.0158,0.08
156,5,PAK,Pakistan,Islamabad,Asia,235824862.0,227196741.0,210969298.0,194454498.0,154369924.0,115414069.0,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
204,95,TJK,Tajikistan,Dushanbe,Asia,9952787.0,9543207.0,8524063.0,7621779.0,6272998.0,5417860.0,4045965.0,2993019.0,143100.0,69.5513,1.0208,0.12
214,111,TKM,Turkmenistan,Ashgabat,Asia,6430770.0,6250438.0,5766431.0,5267970.0,4569132.0,3720278.0,2862903.0,2201432.0,488100.0,13.1751,1.0140,0.08
224,43,UZB,Uzbekistan,Tashkent,Asia,34627652.0,33526656.0,30949417.0,28614227.0,24925554.0,20579100.0,15947129.0,12011361.0,447400.0,77.3975,1.0160,0.43

In [7]:
df2 = df.set_index('Country')
pd.set_option('display.max.rows', 240)
pd.set_option('display.max.columns', 40)

In [8]:
# The index column(which here is 'Country') is not show for axis = 1 even if passed in a list
df2.filter(items = ['Continent', 'Country', 'CCA3', 'Capital'])

                                      Continent CCA3              Capital
Country
Afghanistan                                Asia  AFG                Kabul
Albania                                  Europe  ALB               Tirana
Algeria                                  Africa  DZA              Algiers
American Samoa                          Oceania  ASM            Pago Pago
Andorra                                  Europe  AND     Andorra la Vella
Angola                                   Africa  AGO               Luanda
Anguilla                          North America  AIA           The Valley
Antigua and Barbuda               North America  ATG         Saint John’s
Argentina                         South America  ARG         Buenos Aires
Armenia                                    Asia  ARM              Yerevan
Aruba                             North America  ABW           Oranjestad
Australia                               Oceania  AUS             Canberra
Austria                                  Europe  AUT               Vienna
Azerbaijan                                 Asia  AZE                 Baku
Bahamas                           North America  BHS               Nassau
Bahrain                                    Asia  BHR               Manama
Bangladesh                                 Asia  BGD                Dhaka
Barbados                          North America  BRB           Bridgetown
Belarus                                  Europe  BLR                Minsk
Belgium                                  Europe  BEL             Brussels
Belize                            North America  BLZ             Belmopan
Benin                                    Africa  BEN           Porto-Novo
Bermuda                           North America  BMU             Hamilton
Bhutan                                     Asia  BTN              Thimphu
Bolivia                           South America  BOL                Sucre
Bosnia and Herzegovina                   Europe  BIH             Sarajevo
Botswana                                 Africa  BWA             Gaborone
Brazil                            South America  BRA             Brasilia
British Virgin Islands            North America  VGB            Road Town
Brunei                                     Asia  BRN  Bandar Seri Begawan
Bulgaria                                 Europe  BGR                Sofia
Burkina Faso                             Africa  BFA          Ouagadougou
Burundi                                  Africa  BDI            Bujumbura
Cambodia                                   Asia  KHM           Phnom Penh
Cameroon                                 Africa  CMR              Yaounde
Canada                            North America  CAN               Ottawa
Cape Verde                               Africa  CPV                Praia
Cayman Islands                    North America  CYM          George Town
Central African Republic                 Africa  CAF               Bangui
Chad                                     Africa  TCD            N'Djamena
Chile                             South America  CHL             Santiago
China                                      Asia  CHN              Beijing
Colombia                          South America  COL               Bogota
Comoros                                  Africa  COM               Moroni
Cook Islands                            Oceania  COK               Avarua
Costa Rica                        North America  CRI             San José
Croatia                                  Europe  HRV               Zagreb
Cuba                              North America  CUB               Havana
Curacao                           North America  CUW           Willemstad
Cyprus                                   Europe  CYP              Nicosia
Czech Republic                           Europe  CZE               Prague
Denmark                                  Europe  DNK           Copenhagen
Djibouti                                 Africa  DJI             Djibouti
Dominica                          North America  DMA               Roseau
Dominican Republic                North America  DOM        Santo Domingo
DR Congo                                 Africa  COD             Kinshasa
Ecuador                           South America  ECU                Quito
Egypt                                    Africa  EGY                Cairo
El Salvador                       North America  SLV         San Salvador
Equatorial Guinea                        Africa  GNQ               Malabo
Eritrea                                  Africa  ERI               Asmara
Estonia                                  Europe  EST              Tallinn
Eswatini                                 Africa  SWZ              Mbabane
Ethiopia                                 Africa  ETH          Addis Ababa
Falkland Islands                  South America  FLK              Stanley
Faroe Islands                            Europe  FRO             Tórshavn
Fiji                                    Oceania  FJI                 Suva
Finland                                  Europe  FIN             Helsinki
France                                   Europe  FRA                Paris
French Guiana                     South America  GUF              Cayenne
French Polynesia                        Oceania  PYF              Papeete
Gabon                                    Africa  GAB           Libreville
Gambia                                   Africa  GMB               Banjul
Georgia                                    Asia  GEO              Tbilisi
Germany                                  Europe  DEU               Berlin
Ghana                                    Africa  GHA                Accra
Gibraltar                                Europe  GIB            Gibraltar
Greece                                   Europe  GRC               Athens
Greenland                         North America  GRL                 Nuuk
Grenada                           North America  GRD       Saint George's
Guadeloupe                        North America  GLP          Basse-Terre
Guam                                    Oceania  GUM              Hagåtña
Guatemala                         North America  GTM       Guatemala City
Guernsey                                 Europe  GGY     Saint Peter Port
Guinea                                   Africa  GIN              Conakry
Guinea-Bissau                            Africa  GNB               Bissau
Guyana                            South America  GUY           Georgetown
Haiti                             North America  HTI       Port-au-Prince
Honduras                          North America  HND          Tegucigalpa
Hong Kong                                  Asia  HKG            Hong Kong
Hungary                                  Europe  HUN             Budapest
Iceland                                  Europe  ISL            Reykjavík
India                                      Asia  IND            New Delhi
Indonesia                                  Asia  IDN              Jakarta
Iran                                       Asia  IRN               Tehran
Iraq                                       Asia  IRQ              Baghdad
Ireland                                  Europe  IRL               Dublin
Isle of Man                              Europe  IMN              Douglas
Israel                                     Asia  ISR            Jerusalem
Italy                                    Europe  ITA                 Rome
Ivory Coast                              Africa  CIV         Yamoussoukro
Jamaica                           North America  JAM             Kingston
Japan                                      Asia  JPN                Tokyo
Jersey                                   Europe  JEY         Saint Helier
Jordan                                     Asia  JOR                Amman
Kazakhstan                                 Asia  KAZ            Nursultan
Kenya                                    Africa  KEN              Nairobi
Kiribati                                Oceania  KIR               Tarawa
Kuwait                                     Asia  KWT          Kuwait City
Kyrgyzstan                                 Asia  KGZ              Bishkek
Laos                                       Asia  LAO            Vientiane
Latvia                                   Europe  LVA                 Riga
Lebanon                                    Asia  LBN               Beirut
Lesotho                                  Africa  LSO               Maseru
Liberia                                  Africa  LBR             Monrovia
Libya                                    Africa  LBY              Tripoli
Liechtenstein                            Europe  LIE                Vaduz
Lithuania                                Europe  LTU              Vilnius
Luxembourg                               Europe  LUX           Luxembourg
Macau                                      Asia  MAC    Concelho de Macau
Madagascar                               Africa  MDG         Antananarivo
Malawi                                   Africa  MWI             Lilongwe
Malaysia                                   Asia  MYS         Kuala Lumpur
Maldives                                   Asia  MDV                 Malé
Mali                                     Africa  MLI               Bamako
Malta                                    Europe  MLT             Valletta
Marshall Islands                        Oceania  MHL               Majuro
Martinique                        North America  MTQ       Fort-de-France
Mauritania                               Africa  MRT           Nouakchott
Mauritius                                Africa  MUS           Port Louis
Mayotte                                  Africa  MYT            Mamoudzou
Mexico                            North America  MEX          Mexico City
Micronesia                              Oceania  FSM              Palikir
Moldova                                  Europe  MDA             Chisinau
Monaco                                   Europe  MCO               Monaco
Mongolia                                   Asia  MNG          Ulaanbaatar
Montenegro                               Europe  MNE            Podgorica
Montserrat                        North America  MSR               Brades
Morocco                                  Africa  MAR                Rabat
Mozambique                               Africa  MOZ               Maputo
Myanmar                                    Asia  MMR          Nay Pyi Taw
Namibia                                  Africa  NAM             Windhoek
Nauru                                   Oceania  NRU                Yaren
Nepal                                      Asia  NPL            Kathmandu
Netherlands                              Europe  NLD            Amsterdam
New Caledonia                           Oceania  NCL               Nouméa
New Zealand                             Oceania  NZL           Wellington
Nicaragua                         North America  NIC              Managua
Niger                                    Africa  NER               Niamey
Nigeria                                  Africa  NGA                Abuja
Niue                                    Oceania  NIU                Alofi
North Korea                                Asia  PRK            Pyongyang
North Macedonia                          Europe  MKD               Skopje
Northern Mariana Islands                Oceania  NFK               Saipan
Norway                                   Europe  NOR                 Oslo
Oman                                       Asia  OMN               Muscat
Pakistan                                   Asia  PAK            Islamabad
Palau                                   Oceania  PLW            Ngerulmud
Palestine                                  Asia  PSE             Ramallah
Panama                            North America  PAN          Panama City
Papua New Guinea                        Oceania  PNG         Port Moresby
Paraguay                          South America  PRY             Asunción
Peru                              South America  PER                 Lima
Philippines                                Asia  PHL               Manila
Poland                                   Europe  POL               Warsaw
Portugal                                 Europe  PRT               Lisbon
Puerto Rico                       North America  PRI             San Juan
Qatar                                      Asia  QAT                 Doha
Republic of the Congo                    Africa  COG          Brazzaville
Reunion                                  Africa  REU          Saint-Denis
Romania                                  Europe  ROU            Bucharest
Russia                                   Europe  RUS               Moscow
Rwanda                                   Africa  RWA               Kigali
Saint Barthelemy                  North America  BLM             Gustavia
Saint Kitts and Nevis             North America  KNA           Basseterre
Saint Lucia                       North America  LCA             Castries
Saint Martin                      North America  MAF              Marigot
Saint Pierre and Miquelon         North America  SPM         Saint-Pierre
Saint Vincent and the Grenadines  North America  VCT            Kingstown
Samoa                                   Oceania  WSM                 Apia
San Marino                               Europe  SMR           San Marino
Sao Tome and Principe                    Africa  STP             São Tomé
Saudi Arabia                               Asia  SAU               Riyadh
Senegal                                  Africa  SEN                Dakar
Serbia                                   Europe  SRB             Belgrade
Seychelles                               Africa  SYC             Victoria
Sierra Leone                             Africa  SLE             Freetown
Singapore                                  Asia  SGP            Singapore
Sint Maarten                      North America  SXM          Philipsburg
Slovakia                                 Europe  SVK           Bratislava
Slovenia                                 Europe  SVN            Ljubljana
Solomon Islands                         Oceania  SLB              Honiara
Somalia                                  Africa  SOM            Mogadishu
South Africa                             Africa  ZAF             Pretoria
South Korea                                Asia  KOR                Seoul
South Sudan                              Africa  SSD                 Juba
Spain                                    Europe  ESP               Madrid
Sri Lanka                                  Asia  LKA              Colombo
Sudan                                    Africa  SDN             Khartoum
Suriname                          South America  SUR           Paramaribo
Sweden                                   Europe  SWE            Stockholm
Switzerland                              Europe  CHE                 Bern
Syria                                      Asia  SYR             Damascus
Taiwan                                     Asia  TWN               Taipei
Tajikistan                                 Asia  TJK             Dushanbe
Tanzania                                 Africa  TZA               Dodoma
Thailand                                   Asia  THA              Bangkok
Timor-Leste                                Asia  TLS                 Dili
Togo                                     Africa  TGO                 Lomé
Tokelau                                 Oceania  TKL             Nukunonu
Tonga                                   Oceania  TON           Nuku‘alofa
Trinidad and Tobago               North America  TTO        Port-of-Spain
Tunisia                                  Africa  TUN                Tunis
Turkey                                     Asia  TUR               Ankara
Turkmenistan                               Asia  TKM             Ashgabat
Turks and Caicos Islands          North America  TCA        Cockburn Town
Tuvalu                                  Oceania  TUV             Funafuti
Uganda                                   Africa  UGA              Kampala
Ukraine                                  Europe  UKR                 Kiev
United Arab Emirates                       Asia  ARE            Abu Dhabi
United Kingdom                           Europe  GBR               London
United States                     North America  USA     Washington, D.C.
United States Virgin Islands      North America  VIR     Charlotte Amalie
Uruguay                           South America  URY           Montevideo
Uzbekistan                                 Asia  UZB             Tashkent
Vanuatu                                 Oceania  VUT            Port-Vila
Vatican City                             Europe  VAT         Vatican City
Venezuela                         South America  VEN              Caracas
Vietnam                                    Asia  VNM                Hanoi
Wallis and Futuna                       Oceania  WLF             Mata-Utu
Western Sahara                           Africa  ESH             El Aaiún
Yemen                                      Asia  YEM                Sanaa
Zambia                                   Africa  ZMB               Lusaka
Zimbabwe                                 Africa  ZWE               Harare

In [11]:
df2.filter(items = ['Rank', 'Capital'], axis = 1)

                                  Rank              Capital
Country
Afghanistan                         36                Kabul
Albania                            138               Tirana
Algeria                             34              Algiers
American Samoa                     213            Pago Pago
Andorra                            203     Andorra la Vella
Angola                              42               Luanda
Anguilla                           224           The Valley
Antigua and Barbuda                201         Saint John’s
Argentina                           33         Buenos Aires
Armenia                            140              Yerevan
Aruba                              198           Oranjestad
Australia                           55             Canberra
Austria                             99               Vienna
Azerbaijan                          91                 Baku
Bahamas                            176               Nassau
Bahrain                            154               Manama
Bangladesh                           8                Dhaka
Barbados                           186           Bridgetown
Belarus                             96                Minsk
Belgium                             81             Brussels
Belize                             177             Belmopan
Benin                               77           Porto-Novo
Bermuda                            206             Hamilton
Bhutan                             165              Thimphu
Bolivia                             80                Sucre
Bosnia and Herzegovina             137             Sarajevo
Botswana                           144             Gaborone
Brazil                               7             Brasilia
British Virgin Islands             221            Road Town
Brunei                             175  Bandar Seri Begawan
Bulgaria                           108                Sofia
Burkina Faso                        58          Ouagadougou
Burundi                             78            Bujumbura
Cambodia                            73           Phnom Penh
Cameroon                            53              Yaounde
Canada                              39               Ottawa
Cape Verde                         171                Praia
Cayman Islands                     205          George Town
Central African Republic           117               Bangui
Chad                                69            N'Djamena
Chile                               65             Santiago
China                                1              Beijing
Colombia                            28               Bogota
Comoros                            163               Moroni
Cook Islands                       223               Avarua
Costa Rica                         124             San José
Croatia                            130               Zagreb
Cuba                                85               Havana
Curacao                            189           Willemstad
Cyprus                             158              Nicosia
Czech Republic                      88               Prague
Denmark                            115           Copenhagen
Djibouti                           160             Djibouti
Dominica                           204               Roseau
Dominican Republic                  84        Santo Domingo
DR Congo                            15             Kinshasa
Ecuador                             67                Quito
Egypt                               14                Cairo
El Salvador                        112         San Salvador
Equatorial Guinea                  152               Malabo
Eritrea                            132               Asmara
Estonia                            156              Tallinn
Eswatini                           159              Mbabane
Ethiopia                            12          Addis Ababa
Falkland Islands                   231              Stanley
Faroe Islands                      209             Tórshavn
Fiji                               162                 Suva
Finland                            118             Helsinki
France                              23                Paris
French Guiana                      184              Cayenne
French Polynesia                   183              Papeete
Gabon                              146           Libreville
Gambia                             142               Banjul
Georgia                            131              Tbilisi
Germany                             19               Berlin
Ghana                               47                Accra
Gibraltar                          219            Gibraltar
Greece                              90               Athens
Greenland                          208                 Nuuk
Grenada                            193       Saint George's
Guadeloupe                         178          Basse-Terre
Guam                               191              Hagåtña
Guatemala                           68       Guatemala City
Guernsey                           207     Saint Peter Port
Guinea                              75              Conakry
Guinea-Bissau                      149               Bissau
Guyana                             164           Georgetown
Haiti                               82       Port-au-Prince
Honduras                            89          Tegucigalpa
Hong Kong                          104            Hong Kong
Hungary                             94             Budapest
Iceland                            179            Reykjavík
India                                2            New Delhi
Indonesia                            4              Jakarta
Iran                                17               Tehran
Iraq                                35              Baghdad
Ireland                            125               Dublin
Isle of Man                        202              Douglas
Israel                              98            Jerusalem
Italy                               25                 Rome
Ivory Coast                         52         Yamoussoukro
Jamaica                            139             Kingston
Japan                               11                Tokyo
Jersey                             195         Saint Helier
Jordan                              83                Amman
Kazakhstan                          66            Nursultan
Kenya                               27              Nairobi
Kiribati                           192               Tarawa
Kuwait                             129          Kuwait City
Kyrgyzstan                         110              Bishkek
Laos                               103            Vientiane
Latvia                             151                 Riga
Lebanon                            119               Beirut
Lesotho                            147               Maseru
Liberia                            121             Monrovia
Libya                              107              Tripoli
Liechtenstein                      216                Vaduz
Lithuania                          141              Vilnius
Luxembourg                         168           Luxembourg
Macau                              167    Concelho de Macau
Madagascar                          50         Antananarivo
Malawi                              62             Lilongwe
Malaysia                            45         Kuala Lumpur
Maldives                           174                 Malé
Mali                                59               Bamako
Malta                              173             Valletta
Marshall Islands                   215               Majuro
Martinique                         180       Fort-de-France
Mauritania                         126           Nouakchott
Mauritius                          157           Port Louis
Mayotte                            182            Mamoudzou
Mexico                              10          Mexico City
Micronesia                         194              Palikir
Moldova                            135             Chisinau
Monaco                             217               Monaco
Mongolia                           134          Ulaanbaatar
Montenegro                         169            Podgorica
Montserrat                         230               Brades
Morocco                             40                Rabat
Mozambique                          48               Maputo
Myanmar                             26          Nay Pyi Taw
Namibia                            145             Windhoek
Nauru                              225                Yaren
Nepal                               49            Kathmandu
Netherlands                         71            Amsterdam
New Caledonia                      185               Nouméa
New Zealand                        123           Wellington
Nicaragua                          106              Managua
Niger                               54               Niamey
Nigeria                              6                Abuja
Niue                               232                Alofi
North Korea                         56            Pyongyang
North Macedonia                    150               Skopje
Northern Mariana Islands           210               Saipan
Norway                             120                 Oslo
Oman                               127               Muscat
Pakistan                             5            Islamabad
Palau                              222            Ngerulmud
Palestine                          122             Ramallah
Panama                             128          Panama City
Papua New Guinea                    93         Port Moresby
Paraguay                           109             Asunción
Peru                                44                 Lima
Philippines                         13               Manila
Poland                              37               Warsaw
Portugal                            92               Lisbon
Puerto Rico                        136             San Juan
Qatar                              143                 Doha
Republic of the Congo              114          Brazzaville
Reunion                            161          Saint-Denis
Romania                             64            Bucharest
Russia                               9               Moscow
Rwanda                              76               Kigali
Saint Barthelemy                   228             Gustavia
Saint Kitts and Nevis              211           Basseterre
Saint Lucia                        190             Castries
Saint Martin                       220              Marigot
Saint Pierre and Miquelon          229         Saint-Pierre
Saint Vincent and the Grenadines   199            Kingstown
Samoa                              188                 Apia
San Marino                         218           San Marino
Sao Tome and Principe              187             São Tomé
Saudi Arabia                        41               Riyadh
Senegal                             72                Dakar
Serbia                             105             Belgrade
Seychelles                         196             Victoria
Sierra Leone                       102             Freetown
Singapore                          113            Singapore
Sint Maarten                       214          Philipsburg
Slovakia                           116           Bratislava
Slovenia                           148            Ljubljana
Solomon Islands                    166              Honiara
Somalia                             70            Mogadishu
South Africa                        24             Pretoria
South Korea                         29                Seoul
South Sudan                         86                 Juba
Spain                               30               Madrid
Sri Lanka                           61              Colombo
Sudan                               32             Khartoum
Suriname                           170           Paramaribo
Sweden                              87            Stockholm
Switzerland                        101                 Bern
Syria                               60             Damascus
Taiwan                              57               Taipei
Tajikistan                          95             Dushanbe
Tanzania                            22               Dodoma
Thailand                            20              Bangkok
Timor-Leste                        155                 Dili
Togo                               100                 Lomé
Tokelau                            233             Nukunonu
Tonga                              197           Nuku‘alofa
Trinidad and Tobago                153        Port-of-Spain
Tunisia                             79                Tunis
Turkey                              18               Ankara
Turkmenistan                       111             Ashgabat
Turks and Caicos Islands           212        Cockburn Town
Tuvalu                             227             Funafuti
Uganda                              31              Kampala
Ukraine                             38                 Kiev
United Arab Emirates                97            Abu Dhabi
United Kingdom                      21               London
United States                        3     Washington, D.C.
United States Virgin Islands       200     Charlotte Amalie
Uruguay                            133           Montevideo
Uzbekistan                          43             Tashkent
Vanuatu                            181            Port-Vila
Vatican City                       234         Vatican City
Venezuela                           51              Caracas
Vietnam                             16                Hanoi
Wallis and Futuna                  226             Mata-Utu
Western Sahara                     172             El Aaiún
Yemen                               46                Sanaa
Zambia                              63               Lusaka
Zimbabwe                            74               Harare

In [12]:
df2.filter(like = 'land', axis = 0)

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
British Virgin Islands,221,VGB,Road Town,North America,31305.0,30910.0,29366.0,27556.0,20104.0,15617.0,11109.0,9581.0,151.0,207.3179,1.0059,0.00
Cayman Islands,205,CYM,George Town,North America,68706.0,67311.0,60911.0,54074.0,39658.0,26027.0,17100.0,10533.0,264.0,260.2500,1.0084,0.00
Cook Islands,223,COK,Avarua,Oceania,17011.0,17029.0,17695.0,17212.0,15897.0,17123.0,17651.0,20470.0,236.0,72.0805,1.0005,0.00
Falkland Islands,231,FLK,Stanley,South America,3780.0,3747.0,3408.0,3187.0,3080.0,2332.0,2240.0,2274.0,12173.0,0.3105,1.0043,0.00
Faroe Islands,209,FRO,Tórshavn,Europe,53090.0,52415.0,48816.0,48410.0,45660.0,47479.0,43054.0,38416.0,1393.0,38.1120,1.0038,0.00
Finland,118,FIN,Helsinki,Europe,5540745.0,5529468.0,5479461.0,5363271.0,5176209.0,4986545.0,4779418.0,4606621.0,338424.0,16.3722,1.0009,0.07
Greenland,208,GRL,Nuuk,North America,56466.0,56026.0,55895.0,56351.0,56184.0,55599.0,50106.0,45434.0,2166086.0,0.0261,1.0040,0.00
Iceland,179,ISL,Reykjavík,Europe,372899.0,366669.0,331060.0,318333.0,281462.0,NaN,NaN,204468.0,103000.0,3.6204,1.0069,0.00
Ireland,125,IRL,Dublin,Europe,5023109.0,4946119.0,4665760.0,4524585.0,3768950.0,3485374.0,3391387.0,2937637.0,70273.0,71.4799,1.0073,0.06
Marshall Islands,215,MHL,Majuro,Oceania,41569.0,43413.0,49410.0,53416.0,54224.0,46047.0,31988.0,23969.0,181.0,229.6630,0.9886,0.00
Netherlands,71,NLD,Amsterdam,Europe,17564014.0,17434557.0,17041107.0,16617116.0,15899135.0,14944548.0,14130387.0,13037686.0,41850.0,419.6897,1.0036,0.22
New Zealand,123,NZL,Wellington,Oceania,5185288.0,5061133.0,4590590.0,4346338.0,3855266.0,3397389.0,3147168.0,2824061.0,270467.0,19.1716,1.0108,0.07
Northern Mariana Islands,210,NFK,Saipan,Oceania,49551.0,49587.0,51514.0,54087.0,80338.0,48002.0,17613.0,10143.0,464.0,106.7909,1.0014,0.00
Poland,37,POL,Warsaw,Europe,39857145.0,38428366.0,38553146.0,38597353.0,38504431.0,38064255.0,35521429.0,32482943.0,312679.0,127.4698,1.0404,0.50
Solomon Islands,166,SLB,Honiara,Oceania,724273.0,691191.0,612660.0,540394.0,429978.0,324171.0,233668.0,172833.0,28896.0,25.0648,1.0232,0.01
Switzerland,101,CHE,Bern,Europe,8740472.0,8638613.0,8281732.0,7822435.0,7182059.0,6711693.0,6319113.0,6181227.0,41284.0,211.7157,1.0056,0.11
Thailand,20,THA,Bangkok,Asia,71697030.0,71475664.0,70294397.0,68270489.0,63066603.0,55228410.0,45737753.0,NaN,513120.0,139.7276,1.0013,0.90
Turks and Caicos Islands,212,TCA,Cockburn Town,North America,45703.0,44276.0,36538.0,29726.0,18744.0,11709.0,7598.0,5665.0,948.0,48.2099,1.0131,0.00
United States Virgin Islands,200,VIR,Charlotte Amalie,North America,99465.0,100442.0,102803.0,106142.0,108185.0,100685.0,96640.0,63446.0,347.0,286.6427,0.9937,0.00

In [13]:
df2.iloc[5]

Rank                                   42
CCA3                                  AGO
Capital                            Luanda
Continent                          Africa
2022 Population                35588987.0
2020 Population                33428485.0
2015 Population                28127721.0
2010 Population                23364185.0
2000 Population                16394062.0
1990 Population                11828638.0
1980 Population                 8330047.0
1970 Population                 6029700.0
Area (km²)                      1246700.0
Density (per km²)                 28.5466
Growth Rate                        1.0315
World Population Percentage          0.45
Name: Angola, dtype: object

In [14]:
df[df['Rank'] < 10].sort_values(by = ['Continent', 'Capital'], ascending = [False, True])

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
27,7,BRA,Brazil,Brasilia,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
171,9,RUS,Russia,Moscow,Europe,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,17098242.0,8.4636,0.9973,1.81
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
16,8,BGD,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
149,6,NGA,Nigeria,Abuja,Africa,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74