In [1]:
# Importing the pandas library and giving alias
import pandas as pd

In [2]:
# Reading from a csv file and assigning it to a data frame object
df = pd.read_csv(r"C:\Users\nawaz\Desktop\python for data engineering\datasets\Flavors.csv")

In [35]:
# Grouping up the data by one column
group_by_frame = df.groupby('Base Flavor')

In [64]:
# The grouped data must have an aggregate function to show results
group_by_frame

In [78]:
# Note : mean() and median() functions could not be performed on string type columns
group_by_frame.describe()

            Flavor Rating                                             \
                    count mean       std  min    25%  50%  75%   max
Base Flavor
Chocolate             3.0  8.4  0.346410  8.2  8.200  8.2  8.5   8.8
Vanilla               6.0  5.7  2.710719  2.3  4.025  5.6  6.8  10.0

            Texture Rating            ...             Total Rating         \
                     count      mean  ...    75%  max        count   mean
Base Flavor                           ...
Chocolate              3.0  7.233333  ...  7.350  7.6          3.0  15.70
Vanilla                6.0  5.650000  ...  6.375  8.0          6.0  11.35


                  std   min     25%   50%     75%   max
Base Flavor
Chocolate    0.781025  15.2  15.250  15.3  15.950  16.6
Vanilla      4.263684   5.7   9.025  11.1  13.175  18.0

[2 rows x 24 columns]

In [70]:
group_by_frame.sum()

,Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
Base Flavor,,,,,
Chocolate,ChocolateRocky RoadChocolte Fudge Brownie,YesYesYes,25.2,21.7,47.1
Vanilla,Mint Chocolate ChipVanillaCookie DoughPistachi...,YesNoYesNoYesNo,34.2,33.9,68.1

In [71]:
group_by_frame.count()

             Flavor  Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate         3      3              3               3             3
Vanilla           6      6              6               6             6

In [67]:
# We can perform arbitrary number of aggregate functions on arbitrary number of columns as below :
group_by_frame.agg({'Base Flavor' : ['min', 'max', 'sum', 'count'], 
                               'Flavor Rating' : ['mean', 'median', 'sum', 'max']})

            Base Flavor             \
                    min        max
Base Flavor
Chocolate     Chocolate  Chocolate
Vanilla         Vanilla    Vanilla

                                                              Flavor Rating  \
                                                    sum count          mean
Base Flavor
Chocolate                   ChocolateChocolateChocolate     3           8.4
Vanilla      VanillaVanillaVanillaVanillaVanillaVanilla     6           5.7


            median   sum   max
Base Flavor
Chocolate      8.2  25.2   8.8
Vanilla        5.6  34.2  10.0

In [77]:
# Grouping the data up by multiple columns
df.groupby(['Base Flavor', 'Liked']).max()

                                Flavor  Flavor Rating  Texture Rating  \
Base Flavor Liked
Chocolate   Yes             Rocky Road            8.8             7.6
Vanilla     No                 Vanilla            4.7             5.0
            Yes    Mint Chocolate Chip           10.0             8.0

                   Total Rating
Base Flavor Liked
Chocolate   Yes            16.6
Vanilla     No              9.7
            Yes            18.0